FROM node:8 as dependencies

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm i


FROM node:8

RUN mkdir /app
WORKDIR /app

COPY . /app
RUN rm -rf node_modules

COPY --from=dependencies /app/node_modules /app/node_modules

ENTRYPOINT npm run start -- --host 0.0.0.0
