version: '3.3'

services:

  app:
    container_name: rc-dev
    image: node:8
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 4200:4200
    user: ${UID:-0}:${GID:-0}
    entrypoint: npm start
